backend:
  name: github

media_folder: "static"

collections:
  - name: "profile"
    label: "Profile"
    folder: "/"
    create: false
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Nickname", name: "nickname", widget: "string"}
      - {label: "Picture", name: "picture", widget: "file"}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Interests", name: "interests", widget: "list"}
      - {label: "Friends", name: "friends", widget: "list"}
      - {label: "Links", name: "links", widget: "list"}